before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.monach.us

build:
  stage: build
  script:
    - docker build --pull -t registry.monach.us/docker/autossh-target .
    - docker push registry.monach.us/docker/autossh-target

push_to_docker_hub:
  stage: deploy
  script:
    - docker login -u $HUB_USERNAME -p $HUB_PASSWORD
    - docker tag registry.monach.us/docker/autossh:latest monachus/autossh:latest
    - docker push monachus/autossh
